export const LANG_SR_TRANS = {
    // Frontend validation errors
    required: 'Obavezno polje!',
    email: 'Nevalidan email format!',
    url: 'Nevalidan url format!',
    domain: 'Nevalidan format domene!',
    password: 'Lozinka mora biti dužine bar 8 karaktera, da sadrži malo slovo, veliko slovo, broj i specijalni karakter!',
    // Backend validation errors
    VALIDATION_ERROR: 'Nevalidan unos!',
    'Validation exception': 'Nevalidan unos!',
    CUSTOMER_ID_BAD_INPUT: 'Nevalidan JMBG ili MB!',
    BANK_ACCOUNT_BAD_INPUT: 'Nevalidan Broj računa PB!',
    REFERENCE_NUMBER_BAD_INPUT: 'Nevalidan Poziv na broj!',
    MISSING_REQUEST_DOCUMENT: 'Dokumenti u zahtevu su obavezni!',
    USER_ALREADY_EXISTS: 'Korisnik već postoji',
    // Toast messages success
    success_created: 'Uspešno kreirano!',
    success_edited: 'Uspešno izmenjeno!',
    success_deleted: 'Uspešno obrisano!',
    success_recorded: 'Uspešno snimljeno!',
    success_activation: 'Uspešna aktivacija!',
    success_password_reset: 'Uspešna promena lozinke!',
    success_activation_link: 'Uspešno posla aktivacioni link!',
    success_sent: 'Uspešno poslato!',
    success_unlocked: 'Uspešno otključan korisnik!',
    // Toast messages failure
    SERVER_ERROR: 'Došlo je do greške. Pokušajte ponovo.',
    NOT_VALID: 'Nevalidni ulazni podaci',
    CONTRACT_DATE_ERROR: 'Datum kredita mora biti u prošlosti!',
    UNKNOWN_EXCEPTION: 'Podaci nisu ispravni!',
    BAD_CREDENTIALS: 'Uneti podaci nisu ispravni!',
    USER_NOT_FOUND: 'Nepostojeći korisnik!',
    USER_IS_LOCKED: 'Korisnik je zaključan!',
    password_mismatch: 'Lozinke se ne podudaraju!',
    password_weak: 'Lozinka je slaba!',
    NOT_OLD_PASSWORD: 'Neispravna stara lozinka!',
    PASSWORD_ALREADY_USED: 'Lozinka je već korišćena!',
    PASSWORDS_MATCH: 'Stara lozinka se poklapa sa novom lozinkom!',
    token_expired: 'Vaša sesija je istekla, molim Vas da se ulogujete ponovo!',
    ANALYTICAL_REPORT_NOT_FOUND: 'Nema podataka za kreiranje izveštaja!',
    //table rows (keys are used for sort option)
    id: 'ID',
    newBank: 'Nova Banka',
    prevBank: 'Prethodna Banka',
    name: 'Naziv',
    debtorName: 'Naziv Korisnika',
    debtorId: 'ID Korisnika',
    refStatus: 'Status',
    nextActionDate: 'Alarm',
    updatedDate: 'Poslednja promena',
    code: 'Kod',
    login: 'Email',
    firstName: 'Ime',
    lastName: 'Prezime',
    active: 'Aktivan',
    enabled: 'Logovanje',
    endYear: 'Datum',
    subject: 'Naslov poruke',
    body: 'Poruka',
    categoryType: 'Kategorija',
};
